
# devMode==true...
devMode = false

# Notifies all players with a chat message when a structure upgrade has been triggered
enableStructureUpgradeTriggeredNotification = true

# Warns nearby players when a structure is about to upgrade to the next stage OR if a structure was rejected from upgrading
enableStructureUpgradeWarning = true

# The file path to your general Structures Over Time Config. This file blacklists structures from spawning naturally and allows you to control the stage progression
structureGeneralConfig = "config/HBStructuresGeneralConfig.json"

# The file path to your structure concepts configuration. This file determines the origin structure and order for each structure in your progression chain
structureProgressConfig = "config/HBStructuresConceptConfig.json"

[defaultConceptConfigs]

# Default cycleStage: -1. A structure will 'cycle back' to this stage after its last stage
cycleStage = -1

# Default removeEntities: false. If true, entities in the structure area are removed when a stage ends.
removeEntities = false

# Default stopUpgradeIfSpawnpointSet: true. If true, prevents a structure from upgrading to the next stage if the player has set their spawn point within that structure. This is to prevent players from accidentally losing access to their spawn point when a structure upgrades.
stopUpgradeIfSpawnpointSet = true

# Default stopUpgradeOnDaysSpentInStructure: 8. If a player has woken up (from a bed) at least this number of times then this structure will not upgrade unless forced. Set to -1 to ignore.
stopUpgradeOnDaysSpentInStructure = 8

# Default stopUpgradeOnTotalChestCount: -1. If a structure has more than this number of chests, it will not upgrade to the next stage. This is a good way to assess if a player has used a structure to establish a base and we don't want to overwrite their work. Set to -1 to ignore.
stopUpgradeOnTotalChestCount = -1

# Default uniqueStage: -1. The stage after which only one instance of this structure concept may exist in the world. -1 disables uniqueness.
uniqueStage = -1

# Default upgradeStructureTrigger: 32. By default a structure will upgrade to its next stage after 32 days. You can change this number, set it to an item or dimension name. This setting only changes the default value; edit the value(s) in HBStructuresConceptConfig.json to change it for each structure and stage.
upgradeStructureTrigger = "32"

